# 异常处理

## 学习目标
- 理解“异常是什么？”以及“异常是干什么的？”
- 理解异常的两种处理方式（catch 和 declare）
- 了解异常的三种类型（checked exception, error 和 runtime exception），并理解它们之间的区别
- 掌握如何用 `try-catch-finally` 结构捕获和处理异常
- 掌握如何用 `throws` 从句声明异常
- 掌握如何用 `throw` 语句抛出异常

## 什么是异常(Exception)？

错误在软件开发中时刻发生，有可能是无效的用户输入或者无法回应的外部系统，或者是一个简单的应用程序错误。在这些情况下，我们需要应用程序来处理他们，否则，这些错误会将整个应用程序破坏掉，导致程序无法执行。

所以，*异常就是在执行整个应用程序中出现的错误事件，会阻挡整个程序流程的正常执行。*

### 异常的分类

参考 [The Catch or Specify Requirement](https://docs.oracle.com/javase/tutorial/essential/exceptions/catchOrDeclare.html)
的 The Three Kinds of Exceptions 部分

## 如何处理异常？

异常处理就是在异常发生的地方，通过有效的处理手段，来增加系统的稳定性，不让应用程序中断。通常有两种方式，处理异常和声明异常。

* 处理异常：表示这个异常就地可以解决，一般通过try...catch...语句块来解决。
* 声明异常：表示这个异常在异常发生的地方无法解决，将其抛出去(用throw将锅甩给他人)，并在方法定义中予以声明。

*下面我们将详细介绍:*

### try...catch...finally...

*语法：*
```
try {
    //code
} catch (ExceptionType typeName) {
    // handle exception code
} finally {
    // always come here
}
```

说明：

* *try块*：将一个或者多个语句放入try时，则表示这些语句可能抛出异常。编译器知道可能要发生异常，于是用一个特殊结构评估块内所有语句.
* *catch块*：当问题出现时，一种选择是定义代码块来处理问题，catch块的目的便在于此。catch块是try 块所产生异常的接收者。
* *finally块*：还可以定义finally块，无论运行try块代码的结果如何，该块里面的代码一定运行。在常见的所有环境中，finally块都将运行。无论try块是否运行完，无论是否产生异常，也无论是否在catch块中得到处理，finally 块都将执行。

规则:

* 必须在try之后添加catch或finally块。try块后可同时接catch和finally块，但至少有一个块。
* 必须遵循块顺序：若代码同时使用catch和finally块，则必须将catch块放在try块之后。
* 一个try块可能有多个catch块。若如此，则执行第一个匹配块。
* 一个try块只能有一个finally块。

*举个例子*

```
public int getNumberFromArray(int[] array, int index) {
    try {
        return array[index];
    } catch (ArrayIndexOutOfBoundsException e) {
       System.out.println("数组越界异常：" + e);
    }
}
```

*运行结果：* 当index超过array的长度时，捕获数组越界异常。

### throws/throw 异常

申明异常表示调用某个方法会抛出异常，对这个方法来说，将这个异常抛给它的调用者。而且，也通知了编译器：该方法的任何调用者必须遵守处理或声明规则。

*语法：*

```
public returnType methodName(paramType param) throws ExceptionName {
    // other code
    throw new Exception...
}
```
规则如下：

* throws 关键字放在方法签名的尾部；
* 可以使用 throw 关键字抛出一个异常，无论它是新实例化的还是刚捕获到的。
* 一个方法可以声明抛出多个异常，多个异常之间用逗号隔开。

*举个例子：*

```
public int getNumberFromArray(int[] array, int index) thwors ArrayIndexOutOfBoundsException {
    if (index > array.length) {
        throw new ArrayIndexOutOfBoundsException("数组越界异常");
    }
    return array[index];
}
```

本文仅仅介绍了关于异常的基本知识，对于异常的理解和使用时Java开发的重点，如果想进一步学习如何使用异常，请参考下面的几篇文章：

1. [What Is an Exception](https://docs.oracle.com/javase/tutorial/essential/exceptions/definition.html)
2. [The Catch or Specify Requirement](https://docs.oracle.com/javase/tutorial/essential/exceptions/catchOrDeclare.html)
3. [Catching and Handling Exceptions](https://docs.oracle.com/javase/tutorial/essential/exceptions/handling.html)（忽略 try-with-resources 部分）
4. [Specifying the Exceptions Thrown by a Method](https://docs.oracle.com/javase/tutorial/essential/exceptions/declaring.html)
5. [How to Throw Exceptions](https://docs.oracle.com/javase/tutorial/essential/exceptions/throwing.html)

## Java中常见的异常

Java内置了很多异常，每个异常都有特定的含义，了解特定的异常有助于我们的开发和调试，下面推荐一些文章，请大家自行学习。

1. [List of Java Exceptions](https://programming.guide/java/list-of-java-exceptions.html)
2. [Java Exceptions List](https://examples.javacodegeeks.com/java-exceptions-list-example/#javaExceptions)

## 家庭作业

1. 深入理解异常，总结受检异常和运行时异常的区别以及处理方式。

2. 学习 Java 中常见的异常，并写程序触发至少两种运行时异常。

3. 写一个 divide 方法，接受 a，b 两个参数，返回 a 除以 b 的结果，然后用所学的异常知识来处理 b = 0 时的情况，并打印提示类似”0 不能作为除数“ 的消息

4. 写两个方法 foo() 和 bar()，在 bar() 中构造一个受检异常并抛出，然后在 foo() 中调用 bar() 并捕获异常，打印消息表明异常已经被捕获
